version: '3.6'

services:
  users:
    build:
      context: ./services/back_end
      dockerfile: Dockerfile-dev
    volumes:
      - './services/back_end:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=users.config.BaseConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users
    depends_on:
      - users-db
  rating:
    build:
      context: ./services/back_end
      dockerfile: Dockerfile_rating
    volumes:
      - './services/back_end:/usr/src/app'
    expose:
      - 5001
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=rating.config.BaseConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users
    depends_on:
      - users-db
  users-db:
    build:
      context: ./services/back_end/database
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  client:
      build:
        context: ./services/client
        dockerfile: Dockerfile
      volumes:
        - './services/client:/usr/src/app'
        - '/usr/src/app/node_modules'
      ports:
        - 3007:3000
      environment:
        - NODE_ENV=development
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      depends_on:
        - users
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
